--
- name: install boxfuse
  hosts: www
  become: yes

  tasks:
  - name: step1
    apt:
      name: tomcat8
      state: present
      name: default-jdk
      state: present
      name: git
      state: present
      name: maven
      state: present

  - name: step2
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      dest: /home/dev/hello

  - name: step3
    shell: mvn package chdir=hello

  - name: step4
    copy:
      src: hello/target/hello-1.0.war
      dest: /var/lib/tomcat8/webapps
      remote_src: yes
      directory_mode: yes

  - name: step5
    service:
      name: tomcat8
      state: started

