---
- name: install boxfuse
  hosts: web
  become: yes

  tasks:
  - name: step1
    apt:
      name: tomcat8
      state: present
      name: default-jdk
      state: present
      name: git
      state: present
      name: maven
      state: present

  - name: step2
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      dest: /home/qwe/q1

  - name: step3
    raw: cd q1

  - name: step3.1
    shell:mvn package

  - name: step4
    copy:
      src: boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /usr/local/tomcat/webapps

  - name: step5
    service:
      name: tomcat8
      state: started
